<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>edu.unizg.foi.nwtis.strawberryz</groupId>
  <artifactId>strawberryz_vjezba_07_dz_2</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <name>strawberryz_vjezba_07_dz_2</name>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <java.version>25</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <maven.compiler.release>${java.version}</maven.compiler.release>
    <!-- Plugin versions -->
    <maven.clean>3.5.0</maven.clean>
    <maven.resources>3.4.0</maven.resources>
    <maven.compiler>3.15.0</maven.compiler>
    <maven.surefire>3.5.4</maven.surefire>
    <maven.javadoc>3.12.0</maven.javadoc>
    <maven.dependency>3.10.0</maven.dependency>
    <maven.assembly>3.8.0</maven.assembly>
    <maven.jar>3.5.0</maven.jar>
    <maven.install>3.1.4</maven.install>
    <maven.surefire>3.5.5</maven.surefire>
    <maven.failsafe>3.5.5</maven.failsafe>
    <maven.jlink>3.3.0</maven.jlink>
  </properties>
  <dependencies/>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <version>${maven.clean}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>${maven.resources}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven.compiler}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>${maven.javadoc}</version>
        <configuration>
          <show>private</show>
          <nohelp>true</nohelp>
          <doctitle>NWTiS API ${project.name} ${project.version}</doctitle>
          <windowtitle>NWTiS API for ${project.name}
						${project.version}</windowtitle>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>${maven.jar}</version>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <classpathPrefix>lib/</classpathPrefix>
            </manifest>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <version>${maven.install}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven.surefire}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${maven.failsafe}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jlink-plugin</artifactId>
        <version>${maven.jlink}</version>
        <extensions>true</extensions>
        <configuration>
          <modulePaths>
            <modulePath>
				${env.JAVA_HOME}/jmods/
				</modulePath>
          </modulePaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <modules>
    <module>strawberryz_vjezba_07_dz_2_konfiguracije</module>
    <module>strawberryz_vjezba_07_dz_2_podaci</module>
    <module>strawberryz_vjezba_07_dz_2_kontrola</module>
    <module>strawberryz_vjezba_07_dz_2_rezervacije</module>
    <module>strawberryz_vjezba_07_dz_2_servisi</module>
    <module>strawberryz_vjezba_07_dz_2_dao</module>
    <module>strawberryz_vjezba_07_dz_2_mikroservisi</module>
  </modules>
</project>
