# Define your configuration properties here
kontrola.adresa=20.24.5.2
kontrola.mreznaVrata=8000
kontrola.mreznaVrataAdministracija=8001
kontrola.kodZaKraj=20260329.1

rezervacije.0.adresa=20.24.5.3
rezervacije.0.mreznaVrata=8010
rezervacije.0.mreznaVrataAvioTvrtke=8011
rezervacije.0.mreznaVrataAdministracija=8012
rezervacije.0.kodZaKraj=20260329.2

rezervacije.1.adresa=20.24.5.4
rezervacije.1.mreznaVrata=8010
rezervacije.1.mreznaVrataAvioTvrtke=8011
rezervacije.1.mreznaVrataAdministracija=8012
rezervacije.1.kodZaKraj=20260329.2

korisnickoImeBazaPodataka=nwtis_4
lozinkaBazaPodataka=nwtis#4
upravljacBazaPodataka=org.hsqldb.jdbcDriver
urlBazaPodataka=jdbc:hsqldb:hsql://20.24.5.6:9001/nwtis_4

servisi.adresa=20.24.5.5
servisi.mreznaVrata=8080

servisi.korisnici/mp-rest/url=http://20.24.5.5:8080/api/v1/korisnici
servisi.grupe/mp-rest/url=http://20.24.5.5:8080/api/v1/grupe
servisi.aviotvrtke/mp-rest/url=http://20.24.5.5:8080/api/v1/aviotvrtke

mikroservisi.kontrola/mp-rest/url=http://20.24.5.8:8080/api/v2/kontrola